#!/usr/bin/env bash
# Build crates/prometheus-exec --release so the binary is byte-identical no
# matter which directory the repository is checked out in.
#
# config/prometheus-exec-binary.json pins expectedBuildSha256, so the release
# binary must not depend on the checkout path. Measured 2026-10-04: one commit
# built with plain `cargo build --release` in three checkouts gave three hashes
# (3fd1376d…, 5341d3e0…, 7bd640ac…), so install-prometheus-exec.sh refused
# every build outside the checkout that certified it, i.e. every git worktree.
# Two separate mechanisms leak the path:
#
# 1. Embedded strings. rustc writes absolute source paths into the binary:
#    panic locations, file!(), and build-script OUT_DIR includes. Profile
#    `trim-paths` would strip them but is unstable on the pinned 1.97.1, so the
#    leaking roots are remapped explicitly with --remap-path-prefix.
#
# 2. Symbol hashes. Cargo hashes a path dependency's location into its
#    -C metadata (and so into every mangled symbol and codegen decision)
#    relative to the workspace root ONLY when the dependency is inside that
#    root. substrate/exec-* sits outside crates/prometheus-exec, so its
#    ABSOLUTE path was hashed. Remapping cannot fix that. The build therefore
#    runs in a staged workspace whose virtual root contains
#    crates/prometheus-exec, substrate/exec-* and wit/, making every path dependency
#    workspace-relative. A repo-root [workspace] would do the same but would
#    capture every other Cargo.toml in the tree.
#
# The stage lives in crates/prometheus-exec/target/ (gitignored, per checkout)
# at a fixed path, so cargo's per-workspace build-dir and incremental state
# survive between runs.
#
# Usage: build-prometheus-exec.sh [--print-hash]
#   Builds, copies the binary to crates/prometheus-exec/target/release/, and
#   prints that path, or its sha256 with --print-hash. To recertify, run with
#   --print-hash and write the value to expectedBuildSha256.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
CRATE_DIR="${REPO_ROOT}/crates/prometheus-exec"
STAGE="${CRATE_DIR}/target/reproducible-build"
OUTPUT="${CRATE_DIR}/target/release/prometheus-exec"
PRINT_HASH=false

case "${1:-}" in
    "") ;;
    --print-hash) PRINT_HASH=true ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
esac

sha256_file() {
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        sha256sum "$1" | awk '{print $1}'
    fi
}

# Mirror a source tree into the stage, excluding build output. Preserving
# mtimes keeps cargo's fingerprints valid, so an unchanged tree is not rebuilt.
sync_tree() {
    local src="$1" dst="$2"
    mkdir -p "$dst"
    if command -v rsync >/dev/null 2>&1; then
        rsync -a --delete --exclude /target "$src/" "$dst/"
    else
        rm -rf "$dst"
        mkdir -p "$dst"
        (cd "$src" && tar -cf - --exclude ./target .) | (cd "$dst" && tar -xpf -)
    fi
}

mkdir -p "$STAGE/crates" "$STAGE/substrate"
sync_tree "$CRATE_DIR" "$STAGE/crates/prometheus-exec"
for dep in "$REPO_ROOT"/substrate/exec-*/; do
    dep="${dep%/}"
    sync_tree "$dep" "$STAGE/substrate/$(basename "$dep")"
done
# exec-tier-w runs wasmtime::component::bindgen! against ../../wit at build
# time, so the WIT package is a release input, not just test data.
sync_tree "$REPO_ROOT/wit" "$STAGE/wit"
cp -p "$CRATE_DIR/Cargo.lock" "$STAGE/Cargo.lock"
# resolver must be explicit: a virtual workspace defaults to resolver 1, while
# the crate on its own (edition 2021) resolved features with resolver 2.
# substrate/ is excluded from membership so its dev-dependencies stay out of
# resolution and the committed Cargo.lock still applies (--locked). Cargo's
# workspace-relative path hashing depends only on location under the root, not
# on membership.
cat >"$STAGE/Cargo.toml.next" <<'EOF'
# Generated by scripts/build-prometheus-exec.sh. Do not edit.
[workspace]
resolver = "2"
members = ["crates/prometheus-exec"]
exclude = ["substrate"]
EOF
if cmp -s "$STAGE/Cargo.toml.next" "$STAGE/Cargo.toml"; then
    rm -f "$STAGE/Cargo.toml.next"
else
    mv -f "$STAGE/Cargo.toml.next" "$STAGE/Cargo.toml"
fi

# Build from INSIDE the crate directory: rust-toolchain.toml (copied with the
# crate) is resolved from the current directory, not from --manifest-path, and
# the binary hash depends on the exact rustc.
cd "$STAGE/crates/prometheus-exec"

CARGO_HOME_DIR="${CARGO_HOME:-${HOME}/.cargo}"
CARGO_HOME_DIR="$(cd "$CARGO_HOME_DIR" 2>/dev/null && pwd -P || printf '%s' "$CARGO_HOME_DIR")"

# build-dir is user/repo configuration (templated per workspace path hash), so
# ask cargo where it is rather than assuming target/.
METADATA="$(cargo metadata --format-version 1 --no-deps --locked)"
json_field() {
    printf '%s' "$METADATA" | tr ',' '\n' | awk -F'"' -v key="$1" '$2 == key { print $4; exit }'
}
TARGET_DIR="$(json_field target_directory)"
BUILD_DIR="$(json_field build_directory)"
[ -n "$TARGET_DIR" ] || { echo "cargo metadata reported no target_directory" >&2; exit 1; }
[ -n "$BUILD_DIR" ] || BUILD_DIR="$TARGET_DIR"

# rustc applies the LAST matching remap, so the broad roots come first and the
# narrower stage and build-dir (which can sit inside them) come last. Flags go
# through CARGO_ENCODED_RUSTFLAGS (0x1f-separated) so paths with spaces
# survive, and so ambient RUSTFLAGS or build.rustflags cannot change the
# certified binary.
SEP=$'\x1f'
CARGO_ENCODED_RUSTFLAGS="--remap-path-prefix=${CARGO_HOME_DIR}=/cargo"
CARGO_ENCODED_RUSTFLAGS+="${SEP}--remap-path-prefix=${REPO_ROOT}=/prometheus-skill-pack"
CARGO_ENCODED_RUSTFLAGS+="${SEP}--remap-path-prefix=${STAGE}=/prometheus-skill-pack"
CARGO_ENCODED_RUSTFLAGS+="${SEP}--remap-path-prefix=${BUILD_DIR}=/cargo-build"
export CARGO_ENCODED_RUSTFLAGS
unset RUSTFLAGS

cargo build --release --locked >&2

BUILT="${TARGET_DIR}/release/prometheus-exec"
[ -x "$BUILT" ] || { echo "prometheus-exec build artifact is missing: $BUILT" >&2; exit 1; }
mkdir -p "$(dirname "$OUTPUT")"
install -m 0755 "$BUILT" "$OUTPUT"

if $PRINT_HASH; then
    sha256_file "$OUTPUT"
else
    printf '%s\n' "$OUTPUT"
fi
