#!/usr/bin/env python3
"""Render every agent-context target from rules/src/. Single source, many harnesses.

    rules/src/constitution.md  ─┐
    rules/src/routing.md       ─┼─▶ CLAUDE.md  (AGENTS.md, GEMINI.md → symlinks)
    rules/src/{tech,domain,project}/*.md ─▶ .claude/rules/*.md, <dir>/AGENTS.md, .cursor/rules/*.mdc
    rules/src/routing.md       ───▶ docs/skill-routing.md

`--check` renders to memory, compares with the working tree and exits 1 on any drift or budget breach.
Generated targets are replaced wholesale: a merge would keep files deleted from the source.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "rules" / "src"
CONF = ROOT / "rules" / "build.conf"
HEADER = "<!-- prometheus-rules: v4 · generated by rules/build.sh from rules/src/ — edit the source, never this file -->"
MAX_L0_LINES = 120
MAX_L0_CHARS = 12_500
MAX_RULE_LINES = 80
MAX_NESTED_LINES = 320
ROUTING_MARK = "<!-- routing:layer0 -->"


def read_conf() -> dict[str, str]:
    conf: dict[str, str] = {}
    for raw in CONF.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        conf[key.strip()] = value.strip().strip('"')
    return conf


def split_frontmatter(text: str, name: str) -> tuple[str, str]:
    match = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not match or "paths:" not in match.group(1):
        sys.exit(f"rules/build: {name} has no `paths:` frontmatter — it would load unconditionally")
    return match.group(1), match.group(2)


def routing_layer0(routing: str) -> str:
    """One line per group: **Group:** when → `skill` · when → `skill`."""
    lines: list[str] = []
    for group, body in re.findall(r"^## (.+?)\n(.*?)(?=^## |\Z)", routing, re.S | re.M):
        rows = [r for r in body.splitlines() if r.startswith("|") and not re.match(r"\|\s*-", r)]
        if len(rows) < 2:
            continue
        cells = []
        for row in rows[1:]:
            when, invoke, status = [c.strip() for c in row.strip("|").split("|")][:3]
            note = " _(absent)_" if "absent" in status else ""
            cells.append(f"{when} → {invoke}{note}")
        lines.append(f"- **{group}:** " + " · ".join(cells))
    lines.append(
        "- **No row matches:** `find-skills` → report the top result and its audit status → propose the install; "
        "never install unasked. Install commands and notes: `docs/skill-routing.md`."
    )
    return "\n".join(lines)


def render(conf: dict[str, str], with_cursor: bool) -> tuple[dict[str, str], dict[str, str]]:
    """Return ({relative path: content}, {relative symlink: target})."""
    files: dict[str, str] = {}
    routing = (SRC / "routing.md").read_text()
    constitution = (SRC / "constitution.md").read_text()
    if ROUTING_MARK not in constitution:
        sys.exit("rules/build: constitution.md is missing the routing marker")
    files["CLAUDE.md"] = HEADER + "\n" + constitution.replace(ROUTING_MARK, routing_layer0(routing))
    files["docs/skill-routing.md"] = HEADER + "\n" + routing

    stacks = conf.get("stacks", "").split()
    missing = [s for s in stacks if not (SRC / "tech" / f"{s}.md").is_file()]
    if missing:
        sys.exit(f"rules/build: build.conf lists stacks with no rules/src/tech/<name>.md: {', '.join(missing)}")
    sources: dict[str, str] = {}
    for folder in ("tech", "domain", "project"):
        for path in sorted((SRC / folder).glob("*.md")):
            if path.name == "README.md" or (folder == "tech" and path.stem not in stacks):
                continue
            sources[f"{folder}/{path.stem}"] = path.read_text()

    for key, text in sources.items():
        name = key.split("/", 1)[1]
        front, body = split_frontmatter(text, key)
        files[f".claude/rules/{name}.md"] = f"---\n{front}\n---\n{HEADER}\n{body}"
        if with_cursor:
            globs = re.search(r"paths:\s*\[(.*?)\]", front, re.S)
            glob_list = ",".join(g.strip().strip("'\"") for g in globs.group(1).split(",")) if globs else ""
            files[f".cursor/rules/{name}.mdc"] = f"---\nglobs: {glob_list}\nalwaysApply: false\n---\n{HEADER}\n{body}"

    for entry in conf.get("nested", "").split():
        directory, _, keys = entry.partition(":")
        if not (ROOT / directory).is_dir():
            continue
        parts = [
            HEADER,
            f"# Rules for `{directory}/`",
            "",
            "For harnesses without path-scoped rules. The constitution is the root `AGENTS.md` and is not repeated here.",
            "",
        ]
        for key in keys.split(","):
            if key not in sources:
                sys.exit(f"rules/build: build.conf names unknown source `{key}` for {directory}/")
            parts.append(split_frontmatter(sources[key], key)[1].strip() + "\n")
        files[f"{directory}/AGENTS.md"] = "\n".join(parts)

    return files, {"AGENTS.md": "CLAUDE.md", "GEMINI.md": "CLAUDE.md"}


def budget_errors(files: dict[str, str]) -> list[str]:
    errors: list[str] = []
    layer0 = files["CLAUDE.md"]
    lines, chars = layer0.count("\n"), len(layer0)
    if lines > MAX_L0_LINES:
        errors.append(f"CLAUDE.md is {lines} lines (limit {MAX_L0_LINES}) — apply the placement test, move rules down a layer")
    if chars > MAX_L0_CHARS:
        errors.append(f"CLAUDE.md is {chars} chars (limit {MAX_L0_CHARS})")
    ids = re.findall(r"\*\*A-(\d+) ·", layer0)
    if sorted(map(int, ids)) != list(range(1, 18)):
        errors.append(f"CLAUDE.md must carry A-1…A-17 exactly once each; found {sorted(map(int, ids))}")
    for path, text in files.items():
        count = text.count("\n")
        if path.startswith(".claude/rules/") and count > MAX_RULE_LINES + 1:
            errors.append(f"{path} is {count} lines (limit {MAX_RULE_LINES}) — split the rule or move detail to Layer 3")
        if path.endswith("/AGENTS.md") and count > MAX_NESTED_LINES:
            errors.append(f"{path} is {count} lines (limit {MAX_NESTED_LINES})")
        if re.search(r"^\s*-?\s*\*\*A-\d+ ·", text, re.M) and path != "CLAUDE.md":
            errors.append(f"{path} repeats constitution rule IDs — duplicate constitution")
    return errors


def generated_rule_files() -> list[Path]:
    found: list[Path] = []
    for folder in (ROOT / ".claude" / "rules", ROOT / ".cursor" / "rules"):
        if folder.is_dir():
            found += [p for p in folder.iterdir() if p.suffix in (".md", ".mdc")]
    return found


def check(files: dict[str, str], links: dict[str, str]) -> list[str]:
    drift: list[str] = []
    for rel, content in files.items():
        path = ROOT / rel
        if not path.is_file() or path.is_symlink():
            drift.append(f"missing: {rel}")
        elif path.read_text() != content:
            drift.append(f"drift: {rel}")
    for rel, target in links.items():
        path = ROOT / rel
        if not path.is_symlink() or os.readlink(path) != target:
            drift.append(f"not a symlink to {target}: {rel}")
        elif not path.resolve().is_file():
            drift.append(f"dangling symlink: {rel}")
    expected = {str(ROOT / rel) for rel in files}
    drift += [f"stale generated file: {p.relative_to(ROOT)}" for p in generated_rule_files() if str(p) not in expected]
    return drift


def write(files: dict[str, str], links: dict[str, str]) -> None:
    expected = {str(ROOT / rel) for rel in files}
    for stale in generated_rule_files():
        if str(stale) not in expected:
            stale.unlink()
            print(f"  removed  {stale.relative_to(ROOT)}")
    for rel, content in files.items():
        path = ROOT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        changed = not path.is_file() or path.read_text() != content
        if changed:
            tmp = path.with_suffix(path.suffix + ".tmp")
            tmp.write_text(content)
            tmp.replace(path)
        print(f"  {'wrote  ' if changed else 'current'}  {rel}")
    for rel, target in links.items():
        path = ROOT / rel
        if path.is_symlink() and os.readlink(path) == target:
            print(f"  current  {rel} -> {target}")
            continue
        if path.is_symlink() or path.exists():
            path.unlink()
        path.symlink_to(target)
        print(f"  linked   {rel} -> {target}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify only; exit 1 on drift or budget breach")
    parser.add_argument("--with-cursor", action="store_true", help="also render .cursor/rules/*.mdc")
    args = parser.parse_args()

    conf = read_conf()
    with_cursor = args.with_cursor or conf.get("cursor", "no") == "yes"
    files, links = render(conf, with_cursor)
    problems = budget_errors(files)
    if args.check:
        problems += check(files, links)
    if problems:
        for problem in problems:
            print(f"rules/build: ✗ {problem}", file=sys.stderr)
        return 1
    if args.check:
        layer0 = files["CLAUDE.md"]
        print(f"rules/build: ✓ {len(files)} files and {len(links)} symlinks current; "
              f"CLAUDE.md {layer0.count(chr(10))}/{MAX_L0_LINES} lines, {len(layer0)}/{MAX_L0_CHARS} chars")
        return 0
    write(files, links)
    return 0


if __name__ == "__main__":
    sys.exit(main())
